/*
 * Copyright (c) 2011, 2017 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

package org.glassfish.grizzly.jaxws.addclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AddService", targetNamespace = "http://jaxws.grizzly.glassfish.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddService {


    /**
     * 
     * @param value1
     * @param value2
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://jaxws.grizzly.glassfish.org/", className = "org.glassfish.grizzly.jaxws.addclient.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://jaxws.grizzly.glassfish.org/", className = "org.glassfish.grizzly.jaxws.addclient.AddResponse")
    int add(
            @WebParam(name = "value1", targetNamespace = "")
            int value1,
            @WebParam(name = "value2", targetNamespace = "")
            int value2);

}
